/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.calegario.tela;

import br.com.calegario.dao.ClienteDao;
import br.com.calegario.dao.ClienteDaoImpl;
import br.com.calegario.dao.HibernateUtil;
import br.com.calegario.dao.PedidoDao;
import br.com.calegario.dao.PedidoDaoImpl;
import br.com.calegario.entidade.Cliente;
import br.com.calegario.entidade.Pedido;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Pericleitonrasta
 */
public class PedidoCadastro extends javax.swing.JFrame {

    private Cliente cliente;
    private ClienteDao clienteDao;
    private PedidoDao pedidoDao;
    private Session session;
    private Pedido pedido;
    private Principal telaPai;

    public PedidoCadastro(Principal telaPai) {
        initComponents();
        clienteDao = new ClienteDaoImpl();
        pedidoDao = new PedidoDaoImpl();
        pnPedido.setVisible(false);
        this.telaPai = telaPai;
    }

    public PedidoCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        varTelefone = new javax.swing.JFormattedTextField();
        pnPedido = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        lb_mostrarNomeCliente = new javax.swing.JLabel();
        lb_numPedidos = new javax.swing.JLabel();
        lb_mostrarNumPedidos = new javax.swing.JLabel();
        lb_vlTotal = new javax.swing.JLabel();
        lb_mostrarValorTotal = new javax.swing.JLabel();
        divisor = new javax.swing.JPanel();
        btSalvarPedido = new javax.swing.JButton();
        lb_vlPedido = new javax.swing.JLabel();
        varPreco = new javax.swing.JFormattedTextField();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Cadastro Pedido");

        lbNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNome.setText("Telefone Cliente:");

        btPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        try {
            varTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        varTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        pnPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnPedido.setEnabled(false);

        lb_nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_nome.setText("Cliente:");

        lb_mostrarNomeCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_numPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_numPedidos.setText("Nº Pedidos:");

        lb_mostrarNumPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lb_vlTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_vlTotal.setText("Valor Total:");

        lb_mostrarValorTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        divisor.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout divisorLayout = new javax.swing.GroupLayout(divisor);
        divisor.setLayout(divisorLayout);
        divisorLayout.setHorizontalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        divisorLayout.setVerticalGroup(
            divisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        btSalvarPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btSalvarPedido.setText("Salvar");
        btSalvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarPedidoActionPerformed(evt);
            }
        });

        lb_vlPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_vlPedido.setText("Valor do Pedido: R$");

        varPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        varPreco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnPedidoLayout = new javax.swing.GroupLayout(pnPedido);
        pnPedido.setLayout(pnPedidoLayout);
        pnPedidoLayout.setHorizontalGroup(
            pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidoLayout.createSequentialGroup()
                        .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nome)
                            .addComponent(lb_numPedidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_mostrarNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_mostrarNumPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnPedidoLayout.createSequentialGroup()
                        .addComponent(lb_vlTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_mostrarValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnPedidoLayout.createSequentialGroup()
                        .addComponent(lb_vlPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvarPedido)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        pnPedidoLayout.setVerticalGroup(
            pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_mostrarNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_numPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_mostrarNumPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_vlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_mostrarValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_vlPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvarPedido))
                .addGap(21, 21, 21))
        );

        btVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String telefone = varTelefone.getText().trim();
        if (telefone.length() != 14) {
            JOptionPane.showMessageDialog(null, "Digite um telefone válido.");
        } else {
            try {
                session = HibernateUtil.abrirConexao();
                cliente = clienteDao.pesquisarPorTelefone(telefone, session);
                pnPedido.setVisible(true);
                lb_mostrarNomeCliente.setText(cliente.getNome());
                lb_mostrarNumPedidos.setText(String.valueOf(cliente.getPedidos().size()));
                lb_mostrarValorTotal.setText(String.valueOf(calcularVlTotal(cliente.getPedidos())));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Cliente não cadastrado no sistema.");
            } finally {
                session.close();
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private Double calcularVlTotal(List<Pedido> pedidos) {
        Double vlTotal = 0.0;
        for (Pedido pedido : pedidos) {
            vlTotal += pedido.getValorTotal().doubleValue();
        }
        return vlTotal;
    }

    private void atualizarInfos() {
        try {
            session = HibernateUtil.abrirConexao();
            cliente = clienteDao.pesquisarPorTelefone(varTelefone.getText(), session);
            lb_mostrarNomeCliente.setText(cliente.getNome());
            lb_mostrarNumPedidos.setText(String.valueOf(cliente.getPedidos().size()));
            lb_mostrarValorTotal.setText(String.valueOf(calcularVlTotal(cliente.getPedidos())));
        } catch (Exception e) {
            System.out.println("Erro ao atualizar informações.");
        } finally {
            session.close();
        }
    }

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
        telaPai.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btSalvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarPedidoActionPerformed
        if (varPreco.getText().length() != 0) {
            criarPedido();
            try {
                session = HibernateUtil.abrirConexao();
                pedidoDao.salvarOuAlterar(pedido, session);
                atualizarInfos();
                varPreco.setText("");
                JOptionPane.showMessageDialog(null, "Adicionado com sucesso!");
            } catch (Exception e) {
                System.out.println("Erro ao salvar pedido." + e.getMessage());
            } finally {
                session.close();
            }
        }
    }//GEN-LAST:event_btSalvarPedidoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        telaPai.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void criarPedido() {
        Double preco = Double.parseDouble(varPreco.getText().replaceAll(",", "."));
        session = HibernateUtil.abrirConexao();
        try {
            Integer ultimoNumero = pedidoDao.pesquisarUltimoNumero(session);
            if (ultimoNumero == null) {
                ultimoNumero = 0;
            }
            pedido = new Pedido(null, (ultimoNumero + 1), BigDecimal.valueOf(preco), new Date());
            pedido.setCliente(cliente);
            cliente.getPedidos().add(pedido);
        } catch (Exception e) {
            System.out.println("Erro ao criar pedido." + e.getMessage());
        } finally {
            session.close();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvarPedido;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel divisor;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lb_mostrarNomeCliente;
    private javax.swing.JLabel lb_mostrarNumPedidos;
    private javax.swing.JLabel lb_mostrarValorTotal;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_numPedidos;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_vlPedido;
    private javax.swing.JLabel lb_vlTotal;
    private javax.swing.JPanel pnPedido;
    private javax.swing.JFormattedTextField varPreco;
    private javax.swing.JFormattedTextField varTelefone;
    // End of variables declaration//GEN-END:variables
}
