/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.calegario.tela;

import br.com.calegario.entidade.EnderecoDTO;
import br.com.calegario.ws.CepRest;

/**
 *
 * @author vinicius.kegler
 */
public class PesquisarCep extends javax.swing.JFrame {

    private CepRest cepRest;
    
    public PesquisarCep() {
        initComponents();
        this.pnPesquisa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        varCep = new javax.swing.JTextField();
        lbCep = new javax.swing.JLabel();
        pnPesquisa = new javax.swing.JPanel();
        lbMostrarCep = new javax.swing.JLabel();
        lbMostrarLogra = new javax.swing.JLabel();
        lbMostrarCompl = new javax.swing.JLabel();
        lbMostrarBairro = new javax.swing.JLabel();
        lbMostrarCidade = new javax.swing.JLabel();
        lbMostrarUf = new javax.swing.JLabel();
        lbLograResult = new javax.swing.JLabel();
        lbCepResult = new javax.swing.JLabel();
        lbComplResult = new javax.swing.JLabel();
        lbBairroResult = new javax.swing.JLabel();
        lbCidResult = new javax.swing.JLabel();
        lbUfResult = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Pesquisa Cep");

        varCep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lbCep.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCep.setText("CEP:");

        lbMostrarCep.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMostrarCep.setText("CEP:");

        lbMostrarLogra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMostrarLogra.setText("Logradouro:");

        lbMostrarCompl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMostrarCompl.setText("Complemento:");

        lbMostrarBairro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMostrarBairro.setText("Bairro:");

        lbMostrarCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMostrarCidade.setText("Cidade:");

        lbMostrarUf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbMostrarUf.setText("UF:");

        lbLograResult.setMaximumSize(null);

        lbComplResult.setMaximumSize(null);

        lbBairroResult.setMaximumSize(null);

        lbCidResult.setMaximumSize(null);

        javax.swing.GroupLayout pnPesquisaLayout = new javax.swing.GroupLayout(pnPesquisa);
        pnPesquisa.setLayout(pnPesquisaLayout);
        pnPesquisaLayout.setHorizontalGroup(
            pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPesquisaLayout.createSequentialGroup()
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMostrarCep)
                    .addComponent(lbMostrarLogra)
                    .addComponent(lbMostrarUf)
                    .addComponent(lbMostrarCidade)
                    .addComponent(lbMostrarBairro)
                    .addComponent(lbMostrarCompl))
                .addGap(18, 18, 18)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLograResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbComplResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBairroResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCidResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCepResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        pnPesquisaLayout.setVerticalGroup(
            pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMostrarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCepResult, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMostrarLogra)
                    .addComponent(lbLograResult, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMostrarCompl)
                    .addComponent(lbComplResult, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMostrarBairro)
                    .addComponent(lbBairroResult, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMostrarCidade)
                    .addComponent(lbCidResult, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMostrarUf)
                    .addComponent(lbUfResult, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbCep)
                        .addGap(30, 30, 30)
                        .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addGap(18, 18, 18)
                .addComponent(pnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String cep = this.varCep.getText().trim();
        cepRest = new CepRest();
        EnderecoDTO end = cepRest.pesquisaCep(cep);
        this.trocarValores(end);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void trocarValores(EnderecoDTO endereco){
        this.lbCepResult.setText(endereco.getCep());
        this.lbLograResult.setText(endereco.getLogradouro());
        if(!endereco.getComplemento().isEmpty()){
            this.lbComplResult.setText(endereco.getComplemento());
        }else{
            this.lbComplResult.setText("Sem complemento");
        }
        this.lbBairroResult.setText(endereco.getBairro());
        this.lbCidResult.setText(endereco.getLocalidade());
        this.lbUfResult.setText(endereco.getUf());
        this.pnPesquisa.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarCep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel lbBairroResult;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCepResult;
    private javax.swing.JLabel lbCidResult;
    private javax.swing.JLabel lbComplResult;
    private javax.swing.JLabel lbLograResult;
    private javax.swing.JLabel lbMostrarBairro;
    private javax.swing.JLabel lbMostrarCep;
    private javax.swing.JLabel lbMostrarCidade;
    private javax.swing.JLabel lbMostrarCompl;
    private javax.swing.JLabel lbMostrarLogra;
    private javax.swing.JLabel lbMostrarUf;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUfResult;
    private javax.swing.JPanel pnPesquisa;
    private javax.swing.JTextField varCep;
    // End of variables declaration//GEN-END:variables
}
