/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.calegario.tela;

import br.com.calegario.dao.HibernateUtil;
import br.com.calegario.dao.PedidoDao;
import br.com.calegario.dao.PedidoDaoImpl;
import br.com.calegario.entidade.Usuario;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author vinicius.kegler
 */
public class Principal extends javax.swing.JFrame {

    private Usuario usuarioLogado;
    private PedidoDao pedidoDao;
    private Session session;

    public Principal() {
        initComponents();
    }

    public Principal(Usuario usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
        pedidoDao = new PedidoDaoImpl();
        lb_mostrarTotalPedidos.setText(String.valueOf(atualizarContador()));
    }

    private Integer atualizarContador() {
        session = HibernateUtil.abrirConexao();
        Integer numero = pedidoDao.pesquisarUltimoNumero(session);
        session.close();
        if (numero == null) {
            return 0;
        } else {
            return numero;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_totalPedidos = new javax.swing.JLabel();
        lb_mostrarTotalPedidos = new javax.swing.JLabel();
        btIconeCliente = new javax.swing.JButton();
        btIconePedido = new javax.swing.JButton();
        lb_cliente = new javax.swing.JLabel();
        lb_pedido = new javax.swing.JLabel();
        btPesqPedido = new javax.swing.JButton();
        btPesqCliente = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        mnCliente = new javax.swing.JMenu();
        mnClienteCad = new javax.swing.JMenuItem();
        mnClientePesq = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenu();
        mnPedidoCad = new javax.swing.JMenuItem();
        mnPedidoPesq = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Pizzaria");

        lb_totalPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_totalPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_totalPedidos.setText("Total de pedidos");
        lb_totalPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_mostrarTotalPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_mostrarTotalPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btIconeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/cliente.png"))); // NOI18N
        btIconeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIconeClienteActionPerformed(evt);
            }
        });

        btIconePedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/pizza.png"))); // NOI18N
        btIconePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIconePedidoActionPerformed(evt);
            }
        });

        lb_cliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lb_cliente.setText("Adicionar Cliente");

        lb_pedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lb_pedido.setText("Adicionar Pedido");

        btPesqPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icone-pesquisa.png"))); // NOI18N
        btPesqPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesqPedidoActionPerformed(evt);
            }
        });

        btPesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icone-pesquisa.png"))); // NOI18N
        btPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesqClienteActionPerformed(evt);
            }
        });

        mnCliente.setText("Cliente");

        mnClienteCad.setText("Cadastrar");
        mnClienteCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClienteCadActionPerformed(evt);
            }
        });
        mnCliente.add(mnClienteCad);

        mnClientePesq.setText("Pesquisar");
        mnClientePesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientePesqActionPerformed(evt);
            }
        });
        mnCliente.add(mnClientePesq);

        barraMenu.add(mnCliente);

        mnPedido.setText("Pedido");

        mnPedidoCad.setText("Cadastrar");
        mnPedidoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoCadActionPerformed(evt);
            }
        });
        mnPedido.add(mnPedidoCad);

        mnPedidoPesq.setText("Pesquisar");
        mnPedidoPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoPesqActionPerformed(evt);
            }
        });
        mnPedido.add(mnPedidoPesq);

        barraMenu.add(mnPedido);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_totalPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_mostrarTotalPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btIconeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btIconePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_pedido)
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesqPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_totalPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_mostrarTotalPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIconeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIconePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_cliente)
                    .addComponent(lb_pedido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesqPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnClientePesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientePesqActionPerformed
        this.setVisible(false);
        new ClientePesquisado(this).setVisible(true);
    }//GEN-LAST:event_mnClientePesqActionPerformed

    private void mnClienteCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClienteCadActionPerformed
        this.setVisible(false);
        new ClienteCadastro(this).setVisible(true);
    }//GEN-LAST:event_mnClienteCadActionPerformed

    private void mnPedidoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoCadActionPerformed
        this.setVisible(false);
        new PedidoCadastro(this).setVisible(true);
    }//GEN-LAST:event_mnPedidoCadActionPerformed

    private void btIconeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIconeClienteActionPerformed
        this.setVisible(false);
        new ClienteCadastro(this).setVisible(true);

    }//GEN-LAST:event_btIconeClienteActionPerformed

    private void btIconePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIconePedidoActionPerformed
        this.setVisible(false);
        new PedidoCadastro(this).setVisible(true);

    }//GEN-LAST:event_btIconePedidoActionPerformed

    private void mnPedidoPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoPesqActionPerformed
        String[] opcoes = new String[]{"Sair", "Por data", "Por Cliente"};
        int escolha = JOptionPane.showOptionDialog(null, "Qual tipo de pesquisa?", "Escolha de pesquisa",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, opcoes, opcoes[0]);
        if (escolha == 1) {
            this.setVisible(false);
            new PedidoPesqData(this).setVisible(true);
        }
        if (escolha == 2) {
            this.setVisible(false);
            new PedidoPesqCliente(this).setVisible(true);
        }
    }//GEN-LAST:event_mnPedidoPesqActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btPesqPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesqPedidoActionPerformed
        String[] opcoes = new String[]{"Sair", "Por data", "Por Cliente"};
        int escolha = JOptionPane.showOptionDialog(null, "Qual tipo de pesquisa?", "Escolha de pesquisa",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, opcoes, opcoes[0]);
        if (escolha == 1) {
            this.setVisible(false);
            new PedidoPesqData(this).setVisible(true);
        }
        if (escolha == 2) {
            this.setVisible(false);
            new PedidoPesqCliente(this).setVisible(true);
        }
    }//GEN-LAST:event_btPesqPedidoActionPerformed

    private void btPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesqClienteActionPerformed
        this.setVisible(false);
        new ClientePesquisado(this).setVisible(true);
    }//GEN-LAST:event_btPesqClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btIconeCliente;
    private javax.swing.JButton btIconePedido;
    private javax.swing.JButton btPesqCliente;
    private javax.swing.JButton btPesqPedido;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_mostrarTotalPedidos;
    private javax.swing.JLabel lb_pedido;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_totalPedidos;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenuItem mnClienteCad;
    private javax.swing.JMenuItem mnClientePesq;
    private javax.swing.JMenu mnPedido;
    private javax.swing.JMenuItem mnPedidoCad;
    private javax.swing.JMenuItem mnPedidoPesq;
    // End of variables declaration//GEN-END:variables
}
