/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.calegario.tela;

import br.com.calegario.dao.HibernateUtil;
import br.com.calegario.dao.UsuarioDao;
import br.com.calegario.dao.UsuarioDaoImpl;
import br.com.calegario.entidade.Usuario;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Pericleitonrasta
 */
public class UsuarioCadastro extends javax.swing.JFrame {

    private Session session;
    private UsuarioDao usuarioDao;
    private Usuario usuario;
    private TelaLogin telaPai;
    
    public UsuarioCadastro() {
        initComponents();
        usuarioDao = new UsuarioDaoImpl();
    }

    public UsuarioCadastro(TelaLogin telaLogin) {
        initComponents();
        usuarioDao = new UsuarioDaoImpl();
        telaPai = telaLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_email = new javax.swing.JLabel();
        varLogin = new javax.swing.JTextField();
        lb_titulo = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btCadastro = new javax.swing.JButton();
        lb_nome = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        varSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lb_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_email.setText("Login:");

        varLogin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        varLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varLoginFocusLost(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Cadastro Usuario");

        lb_senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_senha.setText("Senha:");

        btVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btCadastro.setText("Cadastrar");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        lb_nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nome.setText("Nome:");

        varNome.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lb_nome)
                        .addGap(18, 18, 18)
                        .addComponent(varNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCadastro))
                            .addComponent(varSenha))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lb_email)
                        .addGap(17, 17, 17)
                        .addComponent(varLogin)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senha)
                    .addComponent(varSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastro)
                    .addComponent(btVoltar))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
        telaPai.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        if (validarFormulario()) {
            session = HibernateUtil.abrirConexao();
            try {
                usuario = new Usuario(null,
                        varNome.getText().trim(),
                        varLogin.getText().trim(),
                        String.valueOf(varSenha.getPassword()).trim());
                usuarioDao.salvarOuAlterar(usuario, session);
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar usuario.");
                System.out.println(e.getMessage());
            } finally {
                session.close();
                limparCampos();
            }
        }
    }//GEN-LAST:event_btCadastroActionPerformed

    private void limparCampos() {
        varNome.setText("");
        varLogin.setText("");
        varSenha.setText("");
    }

    private void varLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varLoginFocusLost
        String email = varLogin.getText().trim();
        if (email.contains("@")) {
            session = HibernateUtil.abrirConexao();
            boolean existe = usuarioDao.verificarLoginCadastrado(email, session);
            session.close();
            if (existe) {
                JOptionPane.showMessageDialog(null, "Esse e-mail já está cadastrado!");
                varLogin.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "O login tem que ser do tipo e-mail.");
        }
    }//GEN-LAST:event_varLoginFocusLost

    private boolean validarFormulario() {
        String nome = varNome.getText().trim();
        if (verificarCampoMaior3(nome)) {
            JOptionPane.showMessageDialog(null, "O nome tem que ter "
                    + "pelo menos 3 letras.");
            return false;
        }
        String login = varLogin.getText().trim();
        if (verificarLogin(login)) {
            JOptionPane.showMessageDialog(null, "Digite um e-mail correto!");
            return false;
        }
        String senha = String.valueOf(varSenha.getPassword()).trim();
        if (verificarCampoMaior3(senha)) {
            JOptionPane.showMessageDialog(null, "Senha muito fraca.");
            return false;
        }
        return true;
    }

    private boolean verificarCampoMaior3(String campo) {
        return campo.length() < 3;
    }

    private boolean verificarLogin(String login) {
        return !login.contains("@") && !login.contains(".");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField varLogin;
    private javax.swing.JTextField varNome;
    private javax.swing.JPasswordField varSenha;
    // End of variables declaration//GEN-END:variables
}
